### ISSUE TITLE
Uninstall an APP & Youtube Full Screen

### ISSUE THREAD

**Issue by batoceragaming** [uureel/batocera.pro#33]
Hi,

I have a problem with Chromium, After the fresh install it does not work. I am wondering how to uninstall an app? I have deleted the file manually from /userdata/system/pro. But the shortcut in the F1 application persist even after deleting the icon. Is there a proper way to uninstall an app?

I also want to know is there a way to make youtube not full screen in the start? It seems there is a bug that prevent from full screening a video, at first the video appear about 2/3 of the screen, I have to go back to windowed mode (double click) than full screen again to fix this issue for every video. Therefore I asked is there a way to make youtube start in windowed mode?

Many thanks

**Comment by uureel** [comment]
1. after you delete the app's folder from ~/pro icons will automatically clear after restart, updated the installer to use a version that's working 
2. can't replicate and not sure if possible, you'd have to check starting arguments for yttv in ~/pro/youtubetv/Launcher

**Comment by uureel** [comment]
rather something like https://stackoverflow.com/questions/13436855/launch-google-chrome-from-the-command-line-with-specific-window-coordinates 
but batocera runs a forced-fullscreen mode for all apps by default, not sure what your issue is or what's causing it but going around it might need some heavier scripting, might just be more feasible to use a chrome launcher to open yt
